# Generated by Django 2.2.4 on 2019-08-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='customer code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('address', models.CharField(max_length=125, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='state')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telephone')),
                ('mail', models.EmailField(blank=True, max_length=50, null=True, verbose_name='mail')),
                ('zip_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='zip_code')),
                ('importance', models.PositiveSmallIntegerField(default=1, verbose_name='importance')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='contactor name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='contactor description')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='gender')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('note', models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='contactor note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactors', to='customer.Customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'contactors',
                'verbose_name_plural': 'contactors',
                'ordering': ('-name',),
            },
        ),
    ]
