# Generated by Django 2.2.4 on 2019-08-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=20)),
                ('ip_mac', models.CharField(blank=True, max_length=20)),
                ('ip_default', models.CharField(blank=True, max_length=20)),
                ('ip_subnet', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gateway',
            },
        ),
    ]
