# Generated by Django 2.2.4 on 2019-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0002_auto_20190826_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('things', models.ManyToManyField(to='things.Thing')),
            ],
            options={
                'verbose_name': 'Entry',
            },
        ),
    ]
