# Generated by Django 2.2.4 on 2019-08-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0003_auto_20190828_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('rule_type', models.CharField(choices=[(1, 'equal'), (2, 'upper'), (3, 'lower'), (4, 'in range'), (5, 'out range'), (6, 'null')], default=1, max_length=50)),
                ('rule_value', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Thing')),
            ],
            options={
                'verbose_name': 'Rule Engine',
            },
        ),
    ]
