# Generated by Django 2.2.4 on 2019-08-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dev_address', models.SmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('gateway_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.Gateway')),
            ],
            options={
                'verbose_name': 'Device',
                'unique_together': {('name', 'dev_address', 'description')},
            },
        ),
    ]
