# Generated by Django 2.2.4 on 2019-08-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('things_address', models.SmallIntegerField()),
                ('things_type', models.CharField(blank=True, default='Unsinged short', max_length=50)),
                ('things_fcode', models.SmallIntegerField(default=4)),
                ('things_mask', models.CharField(blank=True, default='FFFF', max_length=20)),
                ('things_gain', models.FloatField(default=1)),
                ('things_offset', models.FloatField(default=1)),
                ('things_poll', models.SmallIntegerField(default=1000)),
                ('description', models.TextField(blank=True)),
                ('things_alt', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
            ],
            options={
                'verbose_name': 'Thing',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('things', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Thing')),
            ],
            options={
                'verbose_name': 'Data',
            },
        ),
    ]
