# Generated by Django 2.2.4 on 2019-08-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='ThingData',
        ),
        migrations.AlterModelOptions(
            name='thingdata',
            options={'verbose_name': 'Thing Data'},
        ),
    ]
