# Generated by Django 2.2.4 on 2019-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20190826_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingdata',
            name='conv_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='thingdata',
            name='raw_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='thing',
            name='things_fcode',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (15, '15'), (16, '16')], default=4),
        ),
        migrations.AlterField(
            model_name='thing',
            name='things_type',
            field=models.CharField(choices=[(1, 'Bit'), (2, 'Signed byte'), (3, 'Unsigned byte'), (4, 'Signed short'), (5, 'Unsigned short'), (6, 'Signed int32'), (7, 'Unsigned int32'), (8, 'Float'), (9, 'Signed int64'), (10, 'Unsigned int64'), (11, 'Double')], default=1, max_length=50),
        ),
    ]
