# Generated by Django 2.2.4 on 2019-08-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_auto_20190828_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='things_alt',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
