# Generated by Django 2.2.4 on 2019-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_auto_20190829_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='things_type',
            field=models.SmallIntegerField(choices=[(1, 'Bit'), (2, 'Signed byte'), (3, 'Unsigned byte'), (4, 'Signed short'), (5, 'Unsigned short'), (6, 'Signed int32'), (7, 'Unsigned int32'), (8, 'Float'), (9, 'Signed int64'), (10, 'Unsigned int64'), (11, 'Double')], default=5),
        ),
    ]
